
set(STREAM_ANALYZE_FILE_SRC)

#h264
set(STREAM_ANALYZE_FILE_H264)
include_directories(${STREAM_ANALYZE_PATH}/h264)
file(GLOB_RECURSE STREAM_ANALYZE_FILE_H264 ${STREAM_ANALYZE_PATH}/h264/*.c ${STREAM_ANALYZE_PATH}/h264/*.cc ${STREAM_ANALYZE_PATH}/h264/*.cpp ${STREAM_ANALYZE_PATH}/h264/*.hpp)
#h265
set(STREAM_ANALYZE_FILE_H265)
include_directories(${STREAM_ANALYZE_PATH}/h265)
file(GLOB_RECURSE STREAM_ANALYZE_FILE_H265 ${STREAM_ANALYZE_PATH}/h265/*.c ${STREAM_ANALYZE_PATH}/h265/*.cc ${STREAM_ANALYZE_PATH}/h265/*.cpp ${STREAM_ANALYZE_PATH}/h265/*.hpp)


set(STREAM_ANALYZE_FILE_ROOT)
include_directories(${STREAM_ANALYZE_PATH})
file(GLOB_RECURSE STREAM_ANALYZE_FILE_ROOT ${STREAM_ANALYZE_PATH}/*.c ${STREAM_ANALYZE_PATH}/*.cc ${STREAM_ANALYZE_PATH}/*.cpp ${STREAM_ANALYZE_PATH}/*.hpp)
set(STREAM_ANALYZE_FILE_SRC 
    ${STREAM_ANALYZE_FILE_H264}
    ${STREAM_ANALYZE_FILE_H265}
	${STREAM_ANALYZE_FILE_ROOT}
)